### ISSUE TITLE
Не падаем если на кривой локе, пока билдим ии-сетку

### ISSUE THREAD

**Issue by Hozar2002** [Roman-n/HybridXRay#11]
На кривых локациях с интернета редакторы тупо падают, если мы начинаем генерировать аи сетку (вылет на этапе пред расчёта коллизии). Нашел точку вылета под отладчиком - оказалось но одной из моделей назначен кривой шейдр. Рекомендую добавить ассерт, дабы юзеры понимали что лока кривая, и её надо доделывать.

У себя я просто заглушил этот вылет, так как мне не нужна была правильность всего процесса сборки. Добавить вылет в данном месте не составит труда. [`R_ASSERT2(c_sh, surf->_ShaderXRLCName());`]
![image](https://github.com/Roman-n/HybridXRay/assets/59744335/6a0ef8b7-9ad0-4360-9dab-93ba91cdae82)

**Comment by Roman-n** [comment]
А можно пример шейдера у модели, чтоб повторить у себя? Ну чтоб увидеть, как это происходит.

Попробовал и шейдеры кривые, и ассерт поставил - сетка генерится норм. А размеры локации большие должны быть?

**Comment by Roman-n** [comment]
> на одной из моделей назначен кривой шейдр

И ещё - шейдер, или материал? В борщ СДК есть такая правка:
![000](https://github.com/Roman-n/HybridXRay/assets/33657650/cb2eb99c-e206-4748-b220-0ede3147a683)

**Comment by Hozar2002** [comment]
Заселял локацию `Приять (Живая Зона)`. Вот на этапе построения ИИ сетки оно и вылетало. Исходники скачал с `AP-PRO` с темы мода (там был чей то репак [_**`Link`**_](https://ap-pro.ru/forums/topic/4023-zhivaya-zona-obt/?do=findComment&comment=262425)). На него подкидывал ваши редакторы - те что были в комплекте не стал курить. Вот результаты ассерта что я вставить предлагал
![2024-04-08_19-43-10](https://github.com/Roman-n/HybridXRay/assets/59744335/9ceeb99d-73cc-4eeb-857e-1c2c58ce5e84)
С большой вероятностью проблема именно в кривом репаке (ну либо архив повредился при распаковке, такое тоже случается иногда), но я не стал прям очень сильно ковыряться.

**Comment by Roman-n** [comment]
Ну Живая Зона у меня есть, но чуть по новее, исходники от автора. Но тут с сеткой ещё вопрос - Живая Зона огромная, я в СДК ещё не делал правок для увеличения аи сетки. Попробую, что там и как.

**Comment by Hozar2002** [comment]
> я в СДК ещё не делал правок для увеличения аи сетки

Я сделал у себя базовые правки (я поднимал предел лишь до 24 бит, ибо мне нужна обратная совместимость с пыс системой по размеру, (12 байт кажется, у пыс 11 байт + 1 байт свет, но свет это легаси ебаное, которое не используется никак). Но вот возникла такая беда. Мне не нужны были актуальные исходники локации, ибо я саму локацию перекомпиливать не буду, поэтому и исходники мне нужны +- релизные. Как я и сказал, проблема может быть совсем случайной, но я постараюсь найти суть проблемы.
