### ISSUE TITLE
Не работал хайповый файловый диалог. Вернул как было раньше.

### ISSUE THREAD

**Issue by Hozar2002** [Roman-n/HybridXRay#9]
При попытки открыть какой либо файл неважно в AE или LE приложение намертво зависало. Через отладку студии, если выдалбливать кнопки паузы - оно как то работало, но очень через раз. Собственно у себя я эту тему просто отрубил, и включил олдскульный вариант. 

В идеале в паблик версию завести бы ключик для данной темы, чтоб перманентно можно было врубать старый файлоселектор. Мало ли у кого какая кривая винда, или обнова на винду кривая прилетела. Собственно я саму причину ошибки искать не стал. 

Касательно моих спецификаций. `Win10 Pro - 22H2 (19045.4170)` - оригинальная (не сборка от условного Артура488). 
![image](https://github.com/Roman-n/HybridXRay/assets/59744335/a48f70c0-6d4b-410a-ae1a-027ba82b2bfd)

**Comment by Roman-n** [comment]
> Касательно моих спецификаций. `Win10 Pro - 22H2 (19045.4170)` - оригинальная (не сборка от условного Артура488).

У меня такая же винда, но с подобным не сталкивался.
Да и вообще - этот код для чего нужен? Что-то связанно с Вистой? Я "неважный" программист - может стоит смело его снести?

**Comment by Hozar2002** [comment]
> Да и вообще - этот код для чего нужен?

По идее это новый стиль открытия файлов. В WIndows Vista и выше же полностью переделали проводник (добавили систему интерфейса Aero, которая работает на `GPU`, а не `CPU`). Вот тут вот (https://github.com/Roman-n/HybridXRay/commit/26e20697fc831c9e9fc1aaa8c9c1d865819e5aba) эта система (видимо) была включена. Вообще не понимаю почему, но у меня этот `Windows Vista` диалог открытия файлов не работает. Винду я ставил совсем недавно, может чего не доставилось. `Windows XP` стиль диалога работает нормально (плюс я к нему за столько лет уже привык). 

Есть резон подебажить это в будущем. Если пойму как фиксить напишу решение здесь.

**Comment by Roman-n** [comment]
Да, я понял, вот это старое окно: 
![2](https://github.com/Roman-n/HybridXRay/assets/33657650/66b2f410-f15d-4d55-947a-b95f7b588baa)
А это новое:
![1](https://github.com/Roman-n/HybridXRay/assets/33657650/252980db-4b2d-40a3-89ef-6a246261d00e)
У меня новое работает нормально. Сделаю какой нибудь ключик.
